preset: laravel

disabled:
  - braces
  - concat_without_spaces
  - length_ordered_imports
  - no_blank_lines_between_imports
  - single_import_per_statement

finder:
  exclude:
    - tests
  not-name:
    - index.php
    - server.php
