name: CI

on: [push]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_DATABASE: brain_testing
          MYSQL_USER: forge
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up environment and install dependencies
        run: |
          cp .env.example .env
          composer install -n --prefer-dist --no-ansi --no-progress --no-suggest --no-scripts
          php artisan key:generate

      - name: PHPUnit
        run: |
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -proot -e "CREATE USER 'forge'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';"
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -proot -e "GRANT ALL ON *.* TO 'forge'@'localhost';"
          # mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -proot -e "ALTER USER 'forge'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';"
          vendor/bin/phpunit --testdox --colors=always
